name: Feature request
description: Suggest an idea for Confidant
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Thanks for the suggestion. Please avoid including any secrets."
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What are you trying to do?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds you've tried.
